name: Test and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: [homelab]
    container:
      image: gitea.main-server.home/electronya/electronya-firm-builder:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup West workspace
      run: |
        west update
        west zephyr-export

    - name: Verify environment
      run: |
        pwd
        ls -la
        echo "ZEPHYR_BASE: $ZEPHYR_BASE"
        which gcc
        gcc --version
        which ninja
        west --version

    - name: Build tests with coverage
      run: |
        cd tests/adcAcquisition/filter
        rm -rf build
        cmake -B build -G Ninja \
          -DBOARD=unit_testing \
          -DCOVERAGE=ON \
          || { cat build/CMakeFiles/CMakeOutput.log; cat build/CMakeFiles/CMakeError.log; exit 1; }
        cmake --build build --verbose

    - name: Run tests
      run: |
        cd tests/adcAcquisition/filter
        ./build/testbinary

    - name: Generate coverage report
      run: |
        # Capture coverage
        lcov --capture --directory tests/adcAcquisition/filter/build \
          --output-file coverage.info \
          --rc lcov_branch_coverage=1 \
          --ignore-errors mismatch

        # Filter out test files and system includes
        lcov --remove coverage.info \
          '*/tests/*' \
          '*/zephyr/*' \
          '/usr/*' \
          --output-file coverage.info \
          --rc lcov_branch_coverage=1

        # List coverage summary
        lcov --list coverage.info --rc lcov_branch_coverage=1
